local _, addon = ...

addon.ClassData = {}

addon.ClassData.ClassSpecializationIcons = {
	[62] = 'Interface\\Icons\\Spell_Holy_MagicalSentry',
	[63] = 'Interface\\Icons\\Spell_Fire_FireBolt02',
	[64] = 'Interface\\Icons\\Spell_Frost_FrostBolt02',
	[65] = 'Interface\\Icons\\Spell_Holy_HolyBolt',
	[66] = 'Interface\\Icons\\Ability_Paladin_ShieldoftheTemplar',
	[70] = 'Interface\\Icons\\Spell_Holy_AuraOfLight',
	[71] = 'Interface\\Icons\\Ability_Warrior_SavageBlow',
	[72] = 'Interface\\Icons\\Ability_Warrior_InnerRage',
	[73] = 'Interface\\Icons\\Ability_Warrior_DefensiveStance',
	[102] = 'Interface\\Icons\\Spell_Nature_StarFall',
	[103] = 'Interface\\Icons\\Ability_Druid_CatForm',
	[104] = 'Interface\\Icons\\Ability_Racial_BearForm',
	[105] = 'Interface\\Icons\\Spell_Nature_HealingTouch',
	[250] = 'Interface\\Icons\\Spell_Deathknight_BloodPresence',
	[251] = 'Interface\\Icons\\Spell_Deathknight_FrostPresence',
	[252] = 'Interface\\Icons\\Spell_Deathknight_UnholyPresence',
	[253] = 'INTERFACE\\ICONS\\ability_hunter_bestialdiscipline',
	[254] = 'Interface\\Icons\\Ability_Hunter_FocusedAim',
	[255] = 'INTERFACE\\ICONS\\ability_hunter_camouflage',
	[256] = 'Interface\\Icons\\Spell_Holy_PowerWordShield',
	[257] = 'Interface\\Icons\\Spell_Holy_GuardianSpirit',
	[258] = 'Interface\\Icons\\Spell_Shadow_ShadowWordPain',
	[259] = 'Interface\\Icons\\Ability_Rogue_DeadlyBrew',
	[260] = 'Interface\\Icons\\INV_Sword_30',
	[261] = 'Interface\\Icons\\Ability_Stealth',
	[262] = 'Interface\\Icons\\Spell_Nature_Lightning',
	[263] = 'Interface\\Icons\\Spell_Shaman_ImprovedStormstrike',
	[264] = 'Interface\\Icons\\Spell_Nature_MagicImmunity',
	[265] = 'Interface\\Icons\\Spell_Shadow_DeathCoil',
	[266] = 'Interface\\Icons\\Spell_Shadow_Metamorphosis',
	[267] = 'Interface\\Icons\\Spell_Shadow_RainOfFire',
	[268] = 'Interface\\Icons\\spell_monk_brewmaster_spec',
	[269] = 'Interface\\Icons\\spell_monk_windwalker_spec',
	[270] = 'Interface\\Icons\\spell_monk_mistweaver_spec',
	[577] = 'Interface\\Icons\\ability_demonhunter_specdps',
	[581] = 'Interface\\Icons\\ability_demonhunter_spectank',
	[1467] = 'Interface\\Icons\\classicon_evoker_devastation',
	[1468] = 'Interface\\Icons\\classicon_evoker_preservation',
}

addon.ClassData.ClassList = {
	'WARRIOR',
	'PALADIN',
	'HUNTER',
	'ROGUE',
	'PRIEST',
	'DEATHKNIGHT',
	'SHAMAN',
	'MAGE',
	'WARLOCK',
	'MONK',
	'DRUID',
	'DEMONHUNTER',
	'EVOKER',
}

addon.ClassSpecializationList = {
	['WARRIOR'] = {71, 72, 73},
	['PALADIN'] = {65, 66, 70},
	['HUNTER'] = {253, 254, 255},
	['ROGUE'] = {259, 260, 261},
	['PRIEST'] = {256, 257, 258},
	['DEATHKNIGHT'] = {250, 251, 252},
	['SHAMAN'] = {262, 263, 264},
	['MAGE'] = {62, 63, 64},
	['WARLOCK'] = {265, 266, 267},
	['MONK'] = {268, 269, 270},
	['DRUID'] = {102, 103, 104, 105},
	['DEMONHUNTER'] = {577, 581},
	['EVOKER'] = {1467,1468},
}

addon.ClassData.ClassArmorType = {
	WARRIOR='PLATE',
	PALADIN='PLATE',
	HUNTER='MAIL',
	ROGUE='LEATHER',
	PRIEST='CLOTH',
	DEATHKNIGHT='PLATE',
	SHAMAN='MAIL',
	MAGE='CLOTH',
	WARLOCK='CLOTH',
	MONK='LEATHER',
	DRUID='LEATHER',
	DEMONHUNTER='LEATHER',
	EVOKER='MAIL',
}

addon.ClassData.ClassSpecializationRole = {
	[62] = 'RANGE',
	[63] = 'RANGE',
	[64] = 'RANGE',
	[65] = 'HEAL',
	[66] = 'TANK',
	[70] = 'MELEE',
	[71] = 'MELEE',
	[72] = 'MELEE',
	[73] = 'TANK',
	[102] = 'RANGE',
	[103] = 'MELEE',
	[104] = 'TANK',
	[105] = 'HEAL',
	[250] = 'TANK',
	[251] = 'MELEE',
	[252] = 'MELEE',
	[253] = 'RANGE',
	[254] = 'RANGE',
	[255] = 'MELEE',
	[256] = 'HEAL',
	[257] = 'HEAL',
	[258] = 'RANGE',
	[259] = 'MELEE',
	[260] = 'MELEE',
	[261] = 'MELEE',
	[262] = 'RANGE',
	[263] = 'MELEE',
	[264] = 'HEAL',
	[265] = 'RANGE',
	[266] = 'RANGE',
	[267] = 'RANGE',
	[268] = 'TANK',
	[269] = 'MELEE',
	[270] = 'HEAL',
	[577] = 'MELEE',
	[581] = 'TANK',
	[1467] = 'RANGE',
	[1468] = 'HEAL',
}

addon.ClassData.ClassID = {
	WARRIOR = 1,
	PALADIN = 2,
	HUNTER = 3,
	ROGUE = 4,
	PRIEST = 5,
	DEATHKNIGHT = 6,
	SHAMAN = 7,
	MAGE = 8,
	WARLOCK = 9,
	MONK = 10,
	DRUID = 11,
	DEMONHUNTER = 12,
	EVOKER = 13,
}

function addon.ClassColorNum(class)
	local classColorArray = RAID_CLASS_COLORS[class]
	if classColorArray then
		return classColorArray.r, classColorArray.g, classColorArray.b
	else
		return 0.8,0.8,0.8
	end
end